site_name: AnnoRank
site_url: https://ClaraRus.github.io/AnnoRank/
repo_url: https://github.com/ClaraRus/AnnoRank
edit_uri: blob/master/docs/

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - deduplicate-toc

plugins:
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    watch: [flask_app, src]
    handlers:
      python:
        options:
          show_source: false