name: Deploy docs

on:
  repository_dispatch:
    types: [trigger-mkdocs]

  push:
    branches:
      - mkdocs

  pull_request:
    branches:
      - main
      - mkdocs

jobs:
  deploy-v0:
    name: Build and deploy v0 docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mkdocs branch
        uses: actions/checkout@v3
        with:
          ref: mkdocs
          fetch-depth: 0

      - name: Fetch main branch source code
        run: |
          git fetch origin main
          git checkout origin/main -- flask_app src

      - name: Install Crystal
        uses: oprypin/install-crystal@v1

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python libs
        run: pip install --no-deps -r docs/requirements.txt

      - name: Install Crystal libs
        run: |
          shards init
          shards install

      - name: Build site
        run: mkdocs build

      - name: Configure git for mike
        if: github.event_name != 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy v0 to gh-pages
        if: github.event_name == 'repository_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/mkdocs')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mike deploy --push v0

  deploy-v1:
    name: Build and deploy v1 docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mkdocs branch
        uses: actions/checkout@v3
        with:
          ref: mkdocs
          fetch-depth: 0

      - name: Fetch XAnnoRank branch source code
        run: |
          git fetch origin XAnnoRank
          git checkout origin/XAnnoRank -- flask_app src

      - name: Install Crystal
        uses: oprypin/install-crystal@v1

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python libs
        run: pip install --no-deps -r docs/requirements.txt

      - name: Install Crystal libs
        run: |
          shards init
          shards install

      - name: Build site
        run: mkdocs build

      - name: Configure git for mike
        if: github.event_name == 'push' && github.ref == 'refs/heads/mkdocs'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy v1 to gh-pages and set as default
        if: github.event_name == 'push' && github.ref == 'refs/heads/mkdocs'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mike deploy --push --update-aliases v1 latest
          mike set-default --push latest
